# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 083f06379795672ef7ecff08dbdce1ca522b6b1523af10fa91d292fd626f6602869424c6a7eeae3da932509238a9df719aa4ff7208e07b73548798cfa4666091

test:
  secret_key_base: 956e46108719f8a3812b6395c5cecdd506b766359ae0822eb94fd5bbd683a4ca0a7f4816dcd812b71a5268ff04bc00e33a4c678096411822453eb5983bd36620

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
